"""Added a constraint in reviews

Revision ID: 0a38b86ac47c
Revises: 58bf4ca3dbb1
Create Date: 2024-09-09 16:04:49.541455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a38b86ac47c'
down_revision = '58bf4ca3dbb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_index('ix_destinations_name')
        batch_op.create_index(batch_op.f('ix_destinations_name'), ['name'], unique=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index('ix_users_username', ['username'], unique=True)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_destinations_name'))
        batch_op.create_index('ix_destinations_name', ['name'], unique=False)

    # ### end Alembic commands ###
