"""Add is_admin and price columns on user and destination

Revision ID: 58bf4ca3dbb1
Revises: 944eec4b42c6
Create Date: 2024-09-07 12:00:05.375327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58bf4ca3dbb1'
down_revision = '944eec4b42c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_destinations_name')
        batch_op.create_index(batch_op.f('ix_destinations_name'), ['name'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index('ix_users_username', ['username'], unique=1)
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_destinations_name'))
        batch_op.create_index('ix_destinations_name', ['name'], unique=False)
        batch_op.drop_column('price')

    # ### end Alembic commands ###
